Add integration tests to GitHub Actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,10 +62,34 @@ jobs:
       - name: Run unit tests
         run: make unit-tests
 
+  integration-tests:
+    if: >-
+      (github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'main')) ||
+      (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')) ||
+      (github.event_name == 'release')
+    runs-on: ubuntu-20.04
+    needs: unit-tests
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: "${{ env.PYTHON_VERSION }}"
+      - name: Install dependencies
+        run: |
+          pip install "tox>=${{ env.TOX_MIN_VERSION }}"
+      - name: Run integration tests
+        run: |
+          make ci-deploy
+          # Ensure stack is destroyed at exit, even if tests fail
+          trap "make ci-destroy" EXIT
+          make integration-tests
+
   deploy-dev:
     # Deploy to Dev only on push (including merged PR) to `develop` branch
     if: github.event_name == 'push' && github.event.ref == 'refs/heads/develop'
-    needs: unit-tests
+    needs: integration-tests
     uses: ./.github/workflows/deploy.yml
     with:
       environment: dev
@@ -76,7 +100,7 @@ jobs:
   deploy-prod:
     # Deploy to Prod only on publishing a release (tag) on `main` branch
     if: github.event_name == 'release' && github.event.action == 'published'
-    needs: unit-tests
+    needs: integration-tests
     uses: ./.github/workflows/deploy.yml
     with:
       environment: prod
