Configure GH actions for testing/deployment (#4)
Updated GitHub Actions to trigger testing and deployment
for appropriate actions:

- Run tests on code in "head" branch for all PRs to `develop` or `main`
  (on open, reopen, edit, or synch of a PR)
- Run tests on code in "target" branch for all PRs closed/merged to
  `develop` or `main`
- Deploy to `dev` env on PR close/merge to `develop`
- Deploy to `prod` env on tag/release on `main`

This currently makes use of AWS short-term access keys. The next
step is to use OIDC instead, now that these workflows form a working basis.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,23 +4,131 @@
 name: HLS LPDAAC Historical
 
 on:
+  release:
+    types:
+      - published
   push:
-    branches: [ main ]
+    branches:
+      - main
+      - develop
+    tags-ignore:
+      - '*'
+    paths:
+      - 'cdk/**'
+      - 'src/**'
+      - 'cdk.json'
+      - 'Makefile'
+      - 'setup.py'
+      - 'tox.ini'
   pull_request:
-    branches: [ main ]
+    types:
+      - edited
+      - opened
+      - reopened
+      - synchronize
+    branches:
+      - main
+      - develop
+    paths:
+      - 'cdk/**'
+      - 'src/**'
+      - 'cdk.json'
+      - 'Makefile'
+      - 'setup.py'
+      - 'tox.ini'
+
+defaults:
+  run:
+    shell: bash
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  config:
+    # This is a hack to work around the lack of support for two other possiblities for
+    # avoiding duplication of configuration values:
+    #
+    # (1) YAML anchors (https://yaml.org/spec/1.1/current.html#id899912) and aliases
+    #     (https://yaml.org/spec/1.1/current.html#id902561)
+    # (2) Availability of `env` context within `jobs.<job-id>.with.<with-id>` (see
+    #     https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)
+    #
+    # Alternative hack: https://github.com/actions/runner/issues/1182#issuecomment-1262870831
+    runs-on: ubuntu-22.04
+    outputs:
+      PYTHON_VERSION: "3.9"
+      TOX_MIN_VERSION: "3.18.0"  # `allowlist_externals` replaces `whitelist_externals`
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: "3.9"
-    - name: Install dependencies
-      run: |
-        pip install tox
-    - name: Run tests
-      run: |
-        tox -e py
+      - name: Configure shared values
+        run: ""  # Nothing to do, but at least one step is required
+
+  unit-tests:
+    runs-on: ubuntu-22.04
+    needs: config
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v3
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "${{ needs.config.outputs.PYTHON_VERSION }}"
+      - name: Install dependencies
+        run: |
+          pip install "tox>=${{ needs.config.outputs.TOX_MIN_VERSION }}"
+      - name: Run unit tests
+        run: |
+          make unit-tests
+
+  integration-tests:
+    runs-on: ubuntu-22.04
+    environment: dev
+    needs: config
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v3
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "${{ needs.config.outputs.PYTHON_VERSION }}"
+      - name: Install dependencies
+        run: |
+          pip install "tox>=${{ needs.config.outputs.TOX_MIN_VERSION }}"
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: Run integration tests
+        run: |
+          make ci-deploy
+          # Ensure stack is destroyed at exit, even if tests fail
+          trap "make ci-destroy" EXIT
+          make integration-tests
+
+  deploy-dev:
+    # Deploy to Dev only on push (including merged PR) to `develop` branch
+    if: github.event_name == 'push' && github.event.ref == 'refs/heads/develop'
+    needs:
+      - config
+      - unit-tests
+      - integration-tests
+    uses: ./.github/workflows/deploy.yml
+    with:
+      environment: dev
+      PYTHON_VERSION: "${{ needs.config.outputs.PYTHON_VERSION }}"
+      TOX_MIN_VERSION: "${{ needs.config.outputs.TOX_MIN_VERSION }}"
+    secrets: inherit
+
+  deploy-prod:
+    # Deploy to Prod only on publishing a release (tag) on `main` branch
+    if: github.event_name == 'release' && github.event.action == 'published'
+    needs:
+      - config
+      - unit-tests
+      - integration-tests
+    uses: ./.github/workflows/deploy.yml
+    with:
+      environment: prod
+      PYTHON_VERSION: "${{ needs.config.outputs.PYTHON_VERSION }}"
+      TOX_MIN_VERSION: "${{ needs.config.outputs.TOX_MIN_VERSION }}"
+    secrets: inherit
